import { Conversation } from '@elevenlabs/client';
let conv=null,paused=false,turns=0,messages=[],starting=false;
const $=id=>document.getElementById(id),S=$('status'),W=$('wave'),E=$('error'),hint=$('hint'),fill=$('fill'),pct=$('pct'),start=$('start'),end=$('end'),pause=$('pause'),live=$('live'),results=$('results'),evaluation=$('evaluation');
for(let i=0;i<50;i++){const b=document.createElement('i');b.className='bar';W.appendChild(b)}
function state(x){S.textContent=x;W.classList.toggle('quiet',x!=='Coach is talking'&&x!=='Listening…')}
function prog(){const p=Math.min(92,turns*11);fill.style.width=p+'%';pct.textContent=p+'%'}
function capture(m){const role=m?.source==='user'||m?.role==='user'?'PLAYER':'COACH',text=m?.message||m?.text||m?.content;if(text&&typeof text==='string'){messages.push(role+': '+text);if(role==='PLAYER'){turns++;prog()}}}
async function begin(){if(conv||starting)return;starting=true;E.textContent='';state('Connecting…');hint.textContent='Allow microphone access';try{const mic=await navigator.mediaDevices.getUserMedia({audio:true});mic.getTracks().forEach(t=>t.stop());const r=await fetch('/api/conversation-token',{cache:'no-store'});const token=await r.text();if(!r.ok)throw Error(token||'Could not start voice');conv=await Conversation.startSession({conversationToken:token,onConnect:()=>{state('Listening…');hint.textContent='You can interrupt Coach Johnson';end.style.display='block';start.disabled=true;start.style.opacity='.7'},onDisconnect:()=>state('Call ended'),onError:e=>{E.textContent=e?.message||String(e)},onModeChange:m=>{state(m.mode==='speaking'?'Coach is talking':'Listening…');hint.textContent=m.mode==='speaking'?'Interrupt anytime':'Speak naturally'},onMessage:capture});starting=false}catch(e){starting=false;E.textContent=e?.message||String(e);state('Tap to try again');hint.textContent='Check microphone permission';start.disabled=false}}
start.addEventListener('click',begin);
pause.addEventListener('click',async()=>{if(!conv)return;paused=!paused;try{if(typeof conv.setMicMuted==='function')await conv.setMicMuted(paused);await conv.setVolume({volume:paused?0:1});pause.textContent=paused?'▶ Resume':'Ⅱ Pause';state(paused?'Paused':'Listening…');hint.textContent=paused?'Call paused':'Speak naturally'}catch(e){E.textContent=e?.message||String(e)}});
end.addEventListener('click',async()=>{if(!conv)return;try{await conv.endSession()}catch{}conv=null;live.style.display='none';results.style.display='flex';try{const r=await fetch('/api/score',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({transcript:messages.join('\n')})});const d=await r.json();evaluation.textContent=r.ok?d.text:'Could not score this call. '+d.error}catch(e){evaluation.textContent='Could not score this call. '+e.message}});
prog();